#ifndef ICONS_H
	#define ICONS_H
	#include <Arduino.h>
	extern const unsigned char wifiBitmap [] PROGMEM ;
	// extern const unsigned char battBitmap10 [] PROGMEM;
	// extern const unsigned char lockBitmap10 [] PROGMEM ;
	// extern const unsigned char unlockBitmap10 [] PROGMEM ;
	// extern const unsigned char level1Bitmap [] PROGMEM ;
	// extern const unsigned char level2Bitmap [] PROGMEM ;
	// extern const unsigned char level3Bitmap [] PROGMEM ;
	// extern const unsigned char openBitmap [] PROGMEM ;
	// extern const unsigned char closeBitmap [] PROGMEM ;
	// extern const unsigned char mp3_playerBitmap [] PROGMEM ;
	// extern const unsigned char clock_alarmBitmap [] PROGMEM ;
	extern const unsigned char wifi_icoBitmap [] PROGMEM ;
	extern const unsigned char lightBitmap [] PROGMEM ;
	extern const unsigned char accueilBitmap [] PROGMEM ;
	// extern const unsigned char equalizerBitmap [] PROGMEM ;
	// extern const unsigned char meteoIcon [] PROGMEM ;
	// extern const unsigned char settingsBitmap [] PROGMEM;
	// extern const unsigned char hpBitmap [] PROGMEM ;
	// extern const unsigned char wifi25Bitmap [] PROGMEM ;
	// extern const unsigned char exitBitmap [] PROGMEM ;
	// extern const unsigned char retour_1Bitmap [] PROGMEM ;
	// extern const unsigned char retour_2Bitmap [] PROGMEM ;
	extern const unsigned char playlistBitmap [] PROGMEM ;
	extern const unsigned char settingsLightBitmap [] PROGMEM ;
	// extern const unsigned char sheduleBitmap [] PROGMEM ;
	// extern const unsigned char colorLensBitmap [] PROGMEM ;
	// extern const unsigned char bri_1Bitmap [] PROGMEM ;
	// extern const unsigned char bulbBitmap [] PROGMEM ;
	// extern const unsigned char thermometherbitmap [] PROGMEM ;
	// extern const unsigned char plugbitmap [] PROGMEM ;
	extern const unsigned char epd_bitmap [] PROGMEM ;
	extern const unsigned char rgbsBitmap [] PROGMEM ;
	extern const unsigned char firefox_60x60Bitmap [] PROGMEM ;
	extern const unsigned char youtube_60x60Bitmap [] PROGMEM ;
	extern const unsigned char soundcloud_60x60Bitmap [] PROGMEM ;
	extern const unsigned char windows_60x60Bitmap [] PROGMEM ;
	extern const unsigned char next_40x40Bitmap [] PROGMEM ;
	extern const unsigned char prev_40x40Bitmap [] PROGMEM ;
	extern const unsigned char menu_40x40Bitmap [] PROGMEM ;
	extern const unsigned char volumeUp60x60Bitmap [] PROGMEM ;
	extern const unsigned char volumeMute60x60Bitmap [] PROGMEM ;
	extern const unsigned char volumeDown60x60Bitmap [] PROGMEM ;
	extern const unsigned char pcReset60x60Bitmap [] PROGMEM ;
	extern const unsigned char sublimeText60x60Bitmap [] PROGMEM ;
	extern const unsigned char autoit60x60Bitmap [] PROGMEM ;
	extern const unsigned char netflix60x60Bitmap [] PROGMEM ;
	extern const unsigned char upload_60x60Bitmap [] PROGMEM ;
	extern const unsigned char build_60x60Bitmap [] PROGMEM ;
	extern const unsigned char next_2_60x60Bitmap [] PROGMEM ;
	extern const unsigned char back_2_60x60Bitmap [] PROGMEM ;
	extern const unsigned char vlc_60x60Bitmap [] PROGMEM ;
	extern const unsigned char musicPlayList60x60Bitmap [] PROGMEM ;
	extern const unsigned char random60x60Bitmap [] PROGMEM ;
	extern const unsigned char windows_40x40Bitmap [] PROGMEM ;
	extern const unsigned char windows_40x40Bitmap [] PROGMEM ;
	extern const unsigned char ctrlf2_60x60Bitmap [] PROGMEM ;
	extern const unsigned char space_60x60Bitmap [] PROGMEM ;
#endif // ICONS_H